<a href="https://colab.research.google.com/github/researchandIA/prueba_neural/blob/main/GENERAR_MATRICES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EL CODIGO GENERA MATRICES SIGUIENDO UNA LOGICA DETERMINADA Y SE ASIGNAN UN VALOR PARA EL VECTOR "Y" DE MANERA QUE TENEMOS 2 MATRICES CON DATOS y 2 VECTORES CON INDICES SI  SON VALIDAS O NO LAS MATRICES DE DATOS

In [ ]:
<a href="https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [27]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [28]:
import numpy as np
from random import seed
from random import randint

np.set_printoptions(suppress=True)
seed(1)



def generar_matriz_valida():    

    value=[]
    for i in range(40):
        valor=randint(0, 40)
        if i>10:
            if valor%2 ==1:
                valor=0
        value.append(valor)
    return np.reshape(value,(4,10))



matrices_ok=[]
matrices_ok_y=[]
for n in range(50):
    matrices_ok.append(generar_matriz_valida())
    matrices_ok_y.append(1)

    


def generar_matriz_incorrecta():    

    value=[]
    for i in range(40):
        valor=randint(0, 40)
        
        value.append(valor)
    return np.reshape(value,(4,10))


matrices_nok=[]
matrices_nok_y=[]
for n in range(50):
    matrices_nok.append(generar_matriz_incorrecta())
    matrices_nok_y.append(1)


In [29]:
print(matrices_ok[1])
print(matrices_ok_y[1])

[[14 29 18  1 26 35  6 11 40 18]
 [ 7  0 32  0 32 12  0 18  0  0]
 [32  0  0  2 30  0  0 26  0  0]
 [ 0  0  0 28 32  6 10  0  0  0]]
1


In [30]:
import numpy as np
from random import seed
from random import randint

seed(1)

def generar_matriz_valida():    
# Generamos una matriz donde las posiciones posteriores a la 10 deberan ser pares o 0
    value=[]
    for i in range(40):
        valor=randint(0, 40)
        if i>10:
            if valor%2 ==1:
                valor=0
        value.append(valor)
    return np.reshape(value,(4,10))



matrices_ok=[]
matrices_ok_y=[]
for n in range(50):
  #Generamos una matriz donde puede tomar cualquier valor de 0 a 39
    matrices_ok.append(generar_matriz_valida())
    matrices_ok_y.append(1)

    


def generar_matriz_incorrecta():    

    value=[]
    for i in range(40):
        valor=randint(0, 40)
        
        value.append(valor)
    return np.reshape(value,(4,10))


matrices_nok=[]
matrices_nok_y=[]
for n in range(50):
    matrices_nok.append(generar_matriz_incorrecta())
    matrices_nok_y.append(1)

    


In [33]:
# EJECUTAMOS FUNCION PARA GUARDAR LOS CSV

def exportar_a_csv(matrices_ok,matrices_ok_y,matrices_nok,matrices_nok_y):
        
    a=np.asarray(matrices_ok).reshape(40,50)
    np.savetxt("drive//MyDrive//CSV//matriz_ok_v1.csv",a,delimiter=",",fmt='%i')    
    
        
    np.savetxt("drive//MyDrive//CSV//matriz_ok_y_v1.csv",np.asarray(matrices_ok_y).reshape(1,50),delimiter=",",fmt='%i')
    

    b=np.asarray(matrices_ok).reshape(40,50)
    np.savetxt("drive//MyDrive//CSV//matriz_nok_v1.csv",b,delimiter=",",fmt='%i')

    np.savetxt("drive//MyDrive//CSV//matriz_nok_y_v1.csv",np.asarray(matrices_nok_y).reshape(1,50),delimiter=",",fmt='%i')


  


In [34]:
# EJECUTAMOS FUNCION PARA GUARDAR LOS CSV

exportar_a_csv(matrices_ok,matrices_ok_y,matrices_nok,matrices_nok_y)
  